create or replace PACKAGE TEC_AREA_SUBAREA_SERVICO is
TYPE T_CURSOR IS REF CURSOR;
 
PROCEDURE GetAreas
(
  cdArea in INT,
  curAreas OUT T_CURSOR
);  

PROCEDURE GetSubAreas
(
  cdArea in INT,
  cdSubArea in INT,
  curSubAreas OUT T_CURSOR
);

PROCEDURE GetServicos
(
  cdArea in INT,
  cdSubArea in INT,
  cdServico in INT,
  curServicos OUT T_CURSOR
);
  
end TEC_AREA_SUBAREA_SERVICO;

create or replace PACKAGE BODY TEC_AREA_SUBAREA_SERVICO is

PROCEDURE GetAreas
(
  cdArea in INT,
  curAreas OUT T_CURSOR
) IS
BEGIN
    OPEN curAreas FOR
    SELECT A003_CD_AREA_ATUACAO, 
           A003_DESC_AREA_ATUACAO,
           A003_IND_ATIVO
      FROM VW_AREA_SUBAREA_SERVICOS
     WHERE A003_CD_AREA_ATUACAO = CASE WHEN NVL(cdArea,0) > 0 THEN cdArea ELSE A003_CD_AREA_ATUACAO END
  GROUP BY A003_CD_AREA_ATUACAO, 
           A003_DESC_AREA_ATUACAO,
           A003_IND_ATIVO 
  ORDER BY A003_CD_AREA_ATUACAO;
END GetAreas;  

PROCEDURE GetSubAreas
(
  cdArea in INT,
  cdSubArea in INT,
  curSubAreas OUT T_CURSOR
)IS
BEGIN
    OPEN curSubAreas FOR
    SELECT A004_CD_SUBAREA_ATUACAO, 
           A004_DESC_SUBAREA_ATUACAO,
           A003_IND_ATIVO,
           A004_IND_ATIVO
      FROM VW_AREA_SUBAREA_SERVICOS
     WHERE A003_CD_AREA_ATUACAO = CASE WHEN NVL(cdArea,0) > 0 THEN cdArea ELSE A003_CD_AREA_ATUACAO  END
       AND A004_CD_SUBAREA_ATUACAO  = CASE WHEN NVL(cdSubArea,0) > 0 THEN cdSubArea ELSE A004_CD_SUBAREA_ATUACAO END
  GROUP BY A004_CD_SUBAREA_ATUACAO, 
           A004_DESC_SUBAREA_ATUACAO,
           A003_IND_ATIVO,
           A004_IND_ATIVO
  ORDER BY A004_CD_SUBAREA_ATUACAO;
END GetSubAreas;  

PROCEDURE GetServicos
(
  cdArea in INT,
  cdSubArea in INT,
  cdServico in INT,
  curServicos OUT T_CURSOR
)IS
BEGIN
    OPEN curServicos FOR
    SELECT A005_CD_SERVICO, 
           A005_DESC_SERVICO,
           A003_IND_ATIVO,
           A004_IND_ATIVO,
           A005_IND_ATIVO
     FROM VW_AREA_SUBAREA_SERVICOS
     WHERE A003_CD_AREA_ATUACAO = CASE WHEN NVL(cdArea,0) > 0 THEN cdArea ELSE A003_CD_AREA_ATUACAO END
       AND A004_CD_SUBAREA_ATUACAO  = CASE WHEN NVL(cdSubArea,0) > 0 THEN cdSubArea ELSE A004_CD_SUBAREA_ATUACAO END
       AND A005_CD_SERVICO  = CASE WHEN NVL(cdServico,0) > 0 THEN cdServico ELSE A005_CD_SERVICO END
  GROUP BY A005_CD_SERVICO, 
           A005_DESC_SERVICO,
           A003_IND_ATIVO,
           A004_IND_ATIVO,
           A005_IND_ATIVO
  ORDER BY A005_CD_SERVICO;
END GetServicos;  

end TEC_AREA_SUBAREA_SERVICO;