/*
SOLUTION ONE
*/

SELECT CAST(SUM(TIV_2012) AS DECIMAL(20,2))
  FROM (
   SELECT INS.PID, INS.TIV_2011, INS.TIV_2012, INS.LAT, INS.LON
     FROM INSURANCE (NOLOCK) INS
     JOIN INSURANCE (NOLOCK) INSB ON INSB.TIV_2011 = INS.TIV_2011
	  AND INS.PID <> INSB.PID
	  AND (INSB.LAT <> INS.LAT OR INSB.LON <> INS.LON)
 GROUP BY INS.PID, INS.TIV_2011, INS.TIV_2012, INS.LAT, INS.LON
   HAVING (SELECT COUNT(0) 
			 FROM INSURANCE (NOLOCK) INSC
			WHERE INSC.TIV_2011 <> INS.TIV_2011
			  AND (INSC.LAT = INS.LAT AND INSC.LON = INS.LON)
			  AND INSC.PID <> INS.PID) <= 0) T

/*
SOLUTION TWO
*/

     SELECT CAST(SUM(INS.TIV_2012) AS DECIMAL(20,2))
       FROM INSURANCE (NOLOCK) INS
       JOIN INSURANCE (NOLOCK) INSB ON INSB.TIV_2011 = INS.TIV_2011
        AND INS.PID <> INSB.PID
        AND (INSB.LAT <> INS.LAT OR INSB.LON <> INS.LON)
OUTER APPLY (SELECT COUNT(0) Qty
			   FROM INSURANCE (NOLOCK) INSC
			  WHERE INSC.TIV_2011 <> INS.TIV_2011
			    AND (INSC.LAT = INS.LAT AND INSC.LON = INS.LON)
			    AND INSC.PID <> INS.PID) MT_LN_LO
WHERE ISNULL(MT_LN_LO.Qty,0) = 0